### ISSUE TITLE
 [Frontend]: Adding lisää työpaikka

### ISSUE THREAD

**Issue by Mirazum** [VirittamoHelsinki/saukko-app#343]
### Prerequisites

- [X] I have read the [Git Etiquette](https://github.com/LeDuble/Git-Etiquette). (Required)
- [X] I agree to follow the [Code of Conduct](). (Required)
- [ ] Are you intending to include tests? (Optional)

### Summary (Required)

Adding company from saukko database

### Potential Solution (Required)

fetching the data from saukko database and render it this page

### In which category does the issue belong? (Required)

Feature 🆕 - A new feature.
```[tasklist]
### Tasks
```

**Comment by Mirazum** [comment]
Adding lisää työpaikkä

**Comment by Mirazum** [comment]
#delete it
